development:
  adapter: postgresql
  username: postgres
  host:     localhost
  password: Testadmin1
  encoding: unicode
  database: hrfilter_<%= ENV['USER'] %>_dev
  template: template0
  pool: 5

test:
  adapter: postgresql
  username: postgres
  host:     localhost
  password: Testadmin1
  encoding: unicode
  database: "hrfilter_<%= ENV['LOGNAME'] %>_test"
  template: template0
  pool: 5

